"""empty message

Revision ID: 23d6d2da6c14
Revises: a3a322973b31
Create Date: 2018-10-25 01:08:48.899245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d6d2da6c14'
down_revision = 'a3a322973b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('interests', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_table('events')
    # ### end Alembic commands ###
