"""empty message

Revision ID: 835e616a117f
Revises: 7cf0853da233
Create Date: 2018-10-29 17:38:05.917670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835e616a117f'
down_revision = '7cf0853da233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'comments')
    # ### end Alembic commands ###
